services:
  postgres:
    image: postgres:16-alpine
    container_name: estetica-postgres-dev
    environment:
      POSTGRES_DB: estetica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - estetica_pg_dev:/var/lib/postgresql/data

volumes:
  estetica_pg_dev:
